### PR TITLE
[MIG] mail_attach_existing_attachment: Migration to 18.0

### PR DESCRIPTION
**Pull request by fredericgrall**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm afraid you have lost here the commit history. You should change the commands to have the source branch on the other repo and the target branch in this one.

**Comment by fredericgrall** [comment]
@pedrobaeza, I'm sorry to bother you, can you help me? I changed the destination but when I want to create the pull request, github sees pull request #22 and doesn't allow me to create a new one. Sorry again

**Comment by pedrobaeza** [comment]
From scratch, these are the commands to get the commit history in this repository (assuming you have SSH key in GitHub - if not, replace by https URLs and put credentials each time -):

```bash
git clone git@github.com:OCA/mail.git -b 18.0
cd mail
git remote add social git@github.com:OCA/social.git
git fetch social 17.0
git format-patch --keep-subject --stdout origin/18.0..social/17.0 -- mail_attach_existing_attachment | git am -3 --keep
...
```

**Comment by fredericgrall** [comment]
@pedrobaeza thank you, but my problem is when i want create new pull request 
image
Perhaps delete this pull request

**Comment by pedrobaeza** [comment]
That's because you have pushed the mail branch to this repository, which has a totally different commit history, as said in the bottom line. Do the steps as I have put to retrieve the commit history in this repository history.

**Comment by fredericgrall** [comment]
@pedrobaeza thanks for your help, it's corrected

**Pull request closed without merging**
